### ISSUE TITLE
Simplify installation - dependency definition

### ISSUE THREAD

**Issue by kotoMJ** [kotoMJ/security-showcase-android#36]
Current installation requires to define `android-keystore-compat` itself. But it also requires to list all implementation dependencies.

```
dependencies {
	api("cz.koto:android-keystore-compat:2.0.1") {
		exclude group: 'com.android.support'
	}
	api("cz.koto:android-keystore-compat-base:2.0.1")
	api("cz.koto:android-keystore-compat-19:2.0.1")
	api("cz.koto:android-keystore-compat-21:2.0.1")
	api("cz.koto:android-keystore-compat-23:2.0.1")
	implementation('com.scottyab:rootbeer-lib:0.0.6') {
		exclude group: 'com.android.support'
	}
}
```
  
Fix this ugly installation requirement to simplify gradle definition

**Comment by MjDevCz** [comment]
Will try to reduce need for dependency definition this way: https://android.jlelse.eu/releasing-multi-module-android-library-in-gradle-7286cd667b4b

**Comment by MjDevCz** [comment]
This is fixed in https://github.com/kotoMJ/security-showcase-android/tree/developV3

**Comment by MjDevCz** [comment]
```
dependencies {
        api("cz.kotox:android-keystore-compat-kplus:${versions.keystore_compat}")
}
```
